recipes-core/images/core-image-pelux.bb
The majority of core-image-pelux is copied from core-image-bistro. Since there is already a clear and hard dependency to meta-bistro it would be beneficial to reuse the code.
=> Make core-image-pelux inherit core-image-bistro

recipes-core/images/core-image-pelux-qt.bb, recipes-core/images/core-image-pelux.bb, recipes-qt/automotive/neptune-ui/neptune.service, recipes-qt/automotive/neptune-ui_git.bbappend
Adds an image that includes NeptuneUI. In order to keep a qt free version of the Pelux reference this is done as a new image.
=> Add image with NeptuneUI

recipes-qt/automotive/neptune-ui_git.bbappend
The change has been merged to mainline meta-boot2qt
=> Neptune-ui: remove RDEPENDS

recipes-qt/automotive/neptune-ui/neptune.service
Due to changes in neptune-ui the default QtApplicationManager
config.yaml is not needed to launch the service anymore.
=> neptune-ui: remove default appman config.yaml

recipes-qt/automotive/neptune-ui/neptune.service
Updates the systemd service for neptune so that it works on Pelux after it has been bumped to morty, https://github.com/Pelagicore/pelux-manifests/pull/35.
- Neptunes am-config.yaml is not depending on AppMans config.yaml anymore.
- Set a UTF-8 locale since AppMan will otherwise fail to find one since it doesn't have UTF-8 in its name.
=> neptune-ui: update neptune.service to work with updated meta-boot2qt

recipes-qt/automotive/neptune-ui/neptune.service, recipes-qt/automotive/neptune-ui_git.bbappend
HOME is needed for qtivi's media-simulator backend
qtwebengine is needed for the browser app
qtquickcontrols2 is used by i18n-demo app
=> Neptune fixes

recipes-core/images/core-image-pelux.bb
The following GENIVI components are added:
* dlt-daemon
* node-state-manager
* persistence-client-library
=> core-image-pelux: add GENIVI components

recipes-core/images/core-image-pelux.bb
=> core-image-pelux: add node-state-manager

recipes-core/base-files/base-files/fstab, recipes-core/base-files/base-files_%.bbappend
By default mount /dev/root as a read/write partition.
Singed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>
=> base-files: use default fstab

conf/distro/pelux.conf, recipes-core/images/core-image-pelux.bb
This creates a new "PELUX" distribution that is a derivative of poky.
The pelux distro file contains DISTRO_FEATURES additions and removals.
The core-image-pelux inherits the poky core-image.
IMAGE_FEATURES, IMAGE_INSTALL components and image relevant
definitions are moved to this file.
=> pelux distro: core-image-pelux: inherit poky image

layers/poky/patch/0001-Fix-automated-runtime-testing-using-SystemdbootTarge.patch
testimage extracts the rootfs under test on a test partition and if we
don't explicitly sync the filesystem, it will be performed implicitly
during reboot (when fs is unmounted) and reboot ends up far longer than
testing code would expect it to and hence the testing fails.
Let's explicitly sync filesystems before rebooting the target to ensure
the actual reboot doesn't take long and tests can therefore pass.
=> poky: testimage should sync fs before rebooting

recipes-qt/automotive/qtapplicationmanager_git.bbappend
The nativesdk build was broken because the do_install_append
instructions were valid for the nativesdk version of the recipe. Though
the nativesdk version of the recipe does not include the examples and
the do_install step will fail if the softwarecontainer plugin is not
available.
=> qtapplicationmanager: Fix nativesdk build

recipes-graphics/pango/pango_%.bbappend
GObject introspection for pango needs to run some commands on the native architecture, and uses  qemu for this. For aarch64, these commands cause qemu to crash, so we disable introspection.
=> pango: Disable GObject introspection on aarch64

conf/distro/pelux.conf
This makes it easier to identify the distribution running on a target
system, and it also makes it easier to identify compatible packages in
the build directory of a system.
This patch is meant to go into the Pyro release of PELUX (Yocto 2.3).
Signed-off-by: Jonatan Pålsson <jonatan.palsson@pelagicore.com>
=> distro: Introduce "pelux" as distro name

classes/core-image-pelux.bbclass, recipes-core/images/core-image-pelux-minimal.bb, recipes-core/images/core-image-pelux-qtauto.bb
Modify meta-pelux to make the "core-image-pelux" recipe into a bbclass,
rather than a recipe.
Having core-image-pelux be a bbclass rather than a recipe will allow us
to use the "inherit" directive in our image files, rather than the
"require" directive. "inherit" is preferred, since it does not require
us to specify the path to the bbclass.
Update the existing recipes to work with this change.
=> core-image-pelux: turn recipe into a class

README.md, classes/core-image-pelux.bbclass, conf/distro/pelux.conf, recipes-qt/automotive/qtapplicationmanager-noop.inc, recipes-qt/automotive/qtapplicationmanager-sc.inc, recipes-qt/automotive/qtapplicationmanager_git.bbappend
Make the softwarecontainer package optional, by adding a DISTRO_FEATURE
flag called "process-containment".  In order to keep compatibility with
the existing images, this feature is enabled by default for the "pelux"
images.
Distributions which disable this feature will not have the
softwarecontainer package installed, and therefore might not require the
meta-virtualization layer, which is being pulled in just to satisfy the
softwarecontainer dependencies.
Fixes #33
=> distro: introduce "process-containment" feature

recipes-temporary-patches/gstreamer/gstreamer1.0-plugins-bad_%.bbappend, recipes-temporary-patches/librsvg/librsvg_%.bbappend
These patches are needed to run Neptune on Qt ApplicationManager on Qt 5.9.2 on aarch64
=> Fix appman deps on aarch64

layers/b2qt/recipes-temporary-patches/automotive/qtivi/0001-Don-t-try-to-build-the-ivigenerator-autotests-when-t.patch, layers/b2qt/recipes-temporary-patches/automotive/qtivi_git.bbappend
Temporary fix to allow building qtivi without the ivigenerator
=> qtivi: Fix building without ivigenerator

layers/b2qt/recipes-qt/automotive/qtapplicationmanager-sc.inc
The ${PN} variable in qtapplicationmanager-sc.inc does not appear to
expand properly when it is being assigned using the := operator, so
expand it manually
=> qtapplicationmanager: Fix expansion in inc file

classes/core-image-pelux.bbclass, layers/template-layer/core-image-pelux-template.bb
Also adds an image with the template service installed on it.
Closes #32 
=> Remove template service from pelux bbclass

meta-intel-extras/conf-qt/conf-notes.txt, meta-intel-extras/conf/conf-notes.txt, meta-rpi-extras/conf-qt/conf-notes.txt, meta-rpi-extras/conf/conf-notes.txt
qtauto does not yet work with rpi, that's why that image isn't listed in
the conf-notes yet.
=> bsp layers: update available image names

meta-intel-extras/conf/bblayers.conf.sample, meta-rpi-extras/conf/bblayers.conf.sample
We only need meta-qt5 in our bblayers.conf if we want to build with Qt,
meaning that we want to build the QtAS variant of PELUX. In all other
cases we don't need any Qt support.
Closes #51 
=> bblayers.conf: remove meta-qt5 unless QtAS

classes/core-image-pelux.bbclass, layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune-dev.bb, recipes-core/images/core-image-pelux-minimal-dev.bb
Utils like vim and sftpserver should not be installed in the minimal
version of pelux.
Signed-off-by: Viktor Sjölind <viktor.sjolind@pelagicore.com>
=> Remove package-bistro-utils from bbclass

classes/core-image-pelux.bbclass, layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune-dev.bb, recipes-core/images/core-image-pelux-minimal-dev.bb
These features are typically only needed in a development scenario, so
they should only go into the development images.
=> Splits debug-tweaks and tools-debug to -dev images

layers/b2qt/recipes-qt/automotive/neptune-ui/neptune.service, layers/b2qt/recipes-qt/automotive/neptune-ui_git.bbappend, layers/b2qt/recipes-qt/qt5/qtbase_%.bbappend, layers/b2qt/recipes-qt/qt5/qtwayland_%.bbappend, meta-rpi-extras/recipes-bsp/boot-files/rpi-config_%.bbappend
Perhaps the qtwayland thing should be upstreamed to the qt layers, it could easily be solved with a check on MACHINE and MACHINE_FEATURES or something like that.
=> Prepare the rpi for Qt Auto

conf/variant/intel-qtauto/bblayers.conf.sample, conf/variant/intel/bblayers.conf.sample, conf/variant/rpi-qtauto/bblayers.conf.sample, conf/variant/rpi/bblayers.conf.sample
Apparently, the variant inclusion and BBPATH settings were wrong, which
for some reason never showed up while testing the variant concept
initially. This makes sure the BBPATH is sane (no empty paths in it) and
that local.conf is found properly.
=> conf/variant: fixes an issue with BBPATH

meta-rpi-extras/recipes-bsp/boot-files/rpi-config_%.bbappend
This allows connecting a serial console to the serial pins of the
raspberry pi.
Signed-off-by: Jonatan Pålsson <jonatan.palsson@pelagicore.com>
=> rpi-config: Enable UART

conf/variant/common/local.conf, layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune.bb
The purpose of this PR is to add Qt tools to the SDK produced when running
```bash
bitbake -c populate_sdk core-image-peulx-qtauto-neptune
```
This requrires fixing a conflict in meta-data produced by cmake and qmake when building
the rpms for the SDK. 
The fix is setting `DIRFILES = "1"`. However this only work in `local.conf` and in distro `.conf` but not in `cmake_%.bbappend`
=> fix for qmake in sdk

layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune-dev.bb, recipes-core/images/core-image-pelux-minimal-dev.bb
Despite what's stated in the Yocto docs, it isn't.
=> perf is not an IMAGE_FEATURE

recipes-core/systemd/systemd/10-pelux-ethernet.network, recipes-core/systemd/systemd_%.bbappend
Will bring up any ethernet device by default by using DHCP, and also
sets up resolv.conf in a way so that both systemd and non-systemd aware
applications will work.
=> systemd-networkd: add default DHCP for ethernet

classes/core-image-pelux.bbclass, conf/variant/common/bblayers.conf
This PR just includes the swupdate binary to the default PELUX image. It has been tested to compile and it doesn't break anything. However, swupdate hasn't been proved to be usable for upgrading yet.
Don't merge before https://github.com/Pelagicore/pelux-manifests/pull/119 is merged.
=> Swupdate basic integration

conf/distro/pelux.conf
Applying this patchet results in a: build/tmp/deploy/sdk/pelux-glibc-x86_64-core-image-pelux-minimal-cortexa7hf-neon-vfpv4-toolchain-1.0.sh
This fixes https://github.com/Pelagicore/meta-pelux/issues/90
I also changed the installation path to /opt/pelux-sdk-x86_64/1.0 which, I believe, makes it easier to find and maintain but let me know if you want to keep that change out.
I'll also send a PR to the software factory to reflect those changes.
=> Change SDK name and version to PELUX 1.0

meta-rpi-extras/recipes-support/swupdate/swupdate_%.bbappend, recipes-swupdate/swupdate/swupdate/swupdate.cfg, recipes-swupdate/swupdate/swupdate_%.bbappend
swupdate refuses to run without an /etc/swupdate.cfg. This patchset provides a minimal configuration file that is common and useful for all devices.
Also, the u-boot-fw-utils runtime dependency on the raspberrypi wasn't properly defined by the meta-swupdate's recipe https://github.com/sbabic/meta-swupdate/blob/master/recipes-support/swupdate/swupdate.inc#L77 while I thought it was. This makes sure fw_setenv is included in the generated rootfs.
This patchset has been tested to work.
=> swupdate on raspberrypi3: Add two missing files

meta-intel-extras/recipes-bsp/acpid/acpid_2.%.bbappend, meta-intel-extras/recipes-bsp/acpid/files/powerbtn, meta-intel-extras/recipes-bsp/acpid/files/powerbtn.sh
We want the NUC to respond to power button presses, this is done by
adding an acpi rule with a corresponding script as action, causing the
system to shutdown on press.
=> Add powerbutton script as append to acpi

classes/core-image-pelux.bbclass
This commit is needed to be able to run the smoke tests.
=> core-image-pelux: append swupdate only for rpi

conf/distro/pelux.conf, layers/b2qt/recipes-qt/automotive/neptune-ui_git.bbappend
DISTRO_FEATURE "webengine" is used to enable or disable the use of
qtwebengine in pelux distro.
=> Introduction of DISTRO_FEATURES "webengine" in pelux

classes/core-image-pelux-qtauto.bbclass, layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune.bb
b2qt defines some packagegroups for QtAS addons(neptune-ui is one of the addons) as
well as packagegroups for host & target SDK. PELUX is now using these packagegroups
to introduce these QtAS addons & SDK instead of manually adding each component. One
consequence of using packagegroups from QtAS is that we are introducing additional
addons that were not part of PELUX distribution before.
=> Introduced QtAS packagegroups in PELUX

layers/b2qt/recipes-temporary-patches/qt5/qtbase_%.bbappend
The previous version led to double match if the same recipe was built
more than once. so python (unavailable => python3 (correct) => python33
(didn't work at all!).
=> qtbase_%.bbappend: only match with end of line

classes/core-image-pelux-qtauto.bbclass
The static devs are needed when building HMIs with the SDK.
=> qtauto class: add qtappman static devs in the SDK

scripts/Jenkinsfile
This code is to make sure that when we push changes to meta-pelux,
arp target also gets build.
Signed-off-by: Sapan Das <SKumarDas@luxoft.com>
=> CI job for arp target

classes/core-image-pelux.bbclass, recipes-core/images/core-image-pelux-minimal-dev.bb
QtCreator uses sftp deployment (instead of scp) to "Generic embedded
Linux" devices. Without including an sftp server, it fails with
"The SFTP server finished unexpectedly with exit code 127" but with that
package included, it Just Works(TM).
Signed-off-by: Florent Revest <revestflo@gmail.com>
=> core-image-pelux: Include an sftp server by default

recipes-extended/images/pelux-image-update.inc
Fixed path to sw-description and added SRVREV for it to get rid of the
warnings.
=> pelux-image-update: fix path to sw-description

conf/variant/common/bblayers-qtauto.conf, layers/b2qt/recipes-qt/automotive/neptune3-ui/neptune.service, layers/b2qt/recipes-qt/automotive/neptune3-ui_git.bbappend, layers/b2qt/recipes-qt/automotive/qtapplicationmanager_git.bbappend, layers/b2qt/recipes-qt/qt5/qttools_%.bbappend
This also adapts the bblayers-qtauto.conf to the new setup of meta-b2qt.
The neptune-ui.bbappend got renamed to neptune3-ui.bbappend and fixed.
=> Use neptune3-ui as the new reference ui

meta-intel-extras/recipes-support/swupdate/swupdate_%.bbappend
Both parted and sfdisk are needed to perform swupdate on the Intel
platforms.
=> swupdate: add parted and util-linux-sfdisk to RDEPENDS

recipes-extended/images/pelux-image-update/intel-corei7-64/sw-description
Update the sw-description file to use generic pelux image name
placeholder instead of hardcoded image name.
=> swupdate: update intel sw-description file

layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune-dev.bb
Update core-image-pelux-qtauto-neptune-dev.bb to have ssh-server
as well as sftp-server
:Detail:
An app couldn't be installed from qt-creator due to the lack of sshd.
And Qt-creator use 'sftp' protocol to upload file to the target, therefore sftp-server should be on target as well.
Signed-off-by: Junil Kim <jjunil79.kim@lge.com>
=> core-image-pelux-qtauto: add ssh and sftp servers to dev image

conf/variant/intel-qtauto/local.conf.sample, conf/variant/intel/local.conf.sample
It seems the space before grub-efi was not included as it should.
=> intel: fix image install for grub-efi

scripts/Jenkinsfile
ARP is supported, but does not need to be built in every Jenkinsbuild
=> Jenkinsfile: remove arp

classes/core-image-pelux.bbclass, recipes-core/images/core-image-pelux-minimal-dev.bb
While trying to debug a simple problem of "broken bluetooth" open for 2 months, I noticed that core-image-pelux lacked most of the basic features we could expect from it. For instance, a minimal bash was used as the init process, systemd wasn't used.
I tried to figure out what was going wrong and noticed that the poky's core-image's IMAGE_INSTALL wasn't included. It turns out that our usage of "IMAGE_INSTALL +=" overwrites [core-image's definition of "IMAGE_INSTALL ?=" ](http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/classes/core-image.bbclass#n70)
Replacing those " +=" with "_append =" keeps the core packages such as systemd and bluetooth kernel modules and fixes many problems.
But a question remains... PELUX has been broken for months and no one noticed anything ? What the …
=> Fix installation of core-image components

meta-intel-extras/recipes-kernel/linux/linux-intel_%.bbappend
meta-intel currently points to nonexistent commit in meta-intel.
Temporarily fix by hardcoding SRCREV to latest stable Linux kernel
version of the 4.9 branch.
=> linux-intel: fix SRCREV

meta-intel-extras/recipes-kernel/linux/linux-intel_%.bbappend
This reverts commit c72b97cf295e1d1d4bb9dad179ec324d136e1e08.
The issue has been fixed in meta-intel.
=> Revert "linux-intel: fix SRCREV"

meta-intel-extras/recipes-kernel/linux/files/enable-can.cfg, meta-intel-extras/recipes-kernel/linux/linux-intel_%.bbappend
Enabled Controller Area Network which is needed by the peak-can-driver.
=> linux-intel: enable CAN

recipes-qt/automotive/gammaray_git.bbappend
Fixes the following issue:
do_package_qa: QA Issue: package gammaray contains bad RPATH
in file .../gammaray/usr/lib/libgammaray_core-qt5_10-x86_64.so.2.9.0
=> gammaray: fix rpath

recipes-swupdate/swupdate/swupdate_%.bbappend
Since we don't need swupdate service to start on system boot, disable it.
=> swupdate: disable systemd service

scripts/Jenkinsfile
The variants and images to be built were hardcoded in
JenkinsFile. So if there was a need to add or remove
variants and images, the code needs to be changed. With
this change, a list of variant and images are defined
in Jenkins Environment, which are read dynamically in
JenkinsFile. So adding/removing variants and images do
not require code change.
=> Parameterize variants and images to be built

layers/b2qt/recipes-qt/automotive/qtapplicationmanager-sc.inc
Fixed path to the library and cleaned up syntax a bit.
=> qtapplicationmanager: fix path to library

recipes-devtools/yasm/yasm_1.3.0.bb
Yasm recipe has been removed from poky, while qtwebengine depends on
yasm-native.
=> yasm: add recipe

recipes-temporary-patches/qtscript/qtscript/lto.patch, recipes-temporary-patches/qtscript/qtscript_git.bbappend
This fixes the following compilation issue while building SDK.
Patch has been borrowed from gentooLTO and authored by Shane Peelar.
/tmp/ccqctduy.ltrans0.ltrans.o: In function `ctiVMThrowTrampoline':
<artificial>:(.text+0x4c): undefined reference to `cti_vm_throw'
collect2: error: ld returned 1 exit status
=> qtscript: add bbappend with temp fix for SDK

layers/b2qt/recipes-qt/automotive/neptune3-ui_git.bbappend
Neptune 3 UI assets are not stored at Git LFS, and current recipe from
meta-boot2qt does not seem to check them out at any stage. This change
fixes it.
=> neptune3-ui: checkout assets from git lfs

conf/variant/arp-qtauto/local.conf.sample, conf/variant/arp/local.conf.sample, conf/variant/intel-qtauto/local.conf.sample, conf/variant/intel/local.conf.sample
Bitbake produces the following warning:
NOTE: Multiple providers are available for iasl-native (iasl-native, acpica-native)
Consider defining a PREFERRED_PROVIDER entry to match iasl-native
=> local.conf.sample: set PREFERRED_PROVIDER for iasl-native

recipes-temporary-patches/qtscript/qtscript_git.bbappend
Fixes rpi-qtauto SDK builds.
Building QtScript with GCC 7.3 for ARM with LTO results in a lot of
undefined references to JIT stubs in src/3rdparty/javascriptcore . Looks
like a GCC LTO bug when building for ARM.
QtScript has been deprecated since 5.5 so it is not an important module.
It also seems the main reason for enabling lto for Qt was size (see
c3cc11bc289363203da533e477d4f58a64a79db2 in meta-qt5).
Just disable it.
Signed-off-by: Martin Ejdestig <mejdestig@luxoft.com>
=> qtscript: disable lto on ARM

layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune.bb, recipes-core/images/core-image-pelux-minimal.bb
To avoid potentially different behaviour on dev and non-dev images,
install coreutils on non-dev images as well.
=> core-image-pelux: add coreutils to non-dev images

conf/variant/arp-qtauto/conf-notes.txt, conf/variant/arp/conf-notes.txt, conf/variant/intel-qtauto/conf-notes.txt, conf/variant/intel/conf-notes.txt, conf/variant/qemu-x86-64_nogfx/conf-notes.txt, conf/variant/rpi-qtauto/conf-notes.txt, conf/variant/rpi/conf-notes.txt
To make it clear which variant will be built, print it out when the
poky build-env is being sourced.
=> conf-notes: add variant name to text

scripts/Jenkinsfile
Currently, every pull request and branch build is built against master
branch of the pelux-manifests, which is incorrect since both meta layers
and pelux-manifests follow the Yocto branching strategy, making some of
the branches incompatible between each other.
Build the layer against the corresponding branch of the PELUX manifest
instead, e.g. sumo against sumo and master against master.
=> Jenkinsfile: build against analogous manifest branch

layers/b2qt/recipes-qt/automotive/qtapplicationmanager_git.bbappend
This fix is required to make appman and neptune 3 ui be in sync.
Since the manifest has been updated to 5.12 this patch is not
needed anymore.
=> qtapplicationmanager: Removed explicit hash

recipes-temporary-patches/gammaray/gammaray_git.bbappend
Removed bbappend as the rparth issue has been finally fixed in
Gammaray 5.12.
(cherry picked from commit 27331572026b0a3fb467846d2beee893dd16180d)
=> gammaray: remove bbappend

classes/core-image-pelux.bbclass
Mopidy installation is broken in thud due to python2 support being
dropped by Yocto and mopidy not suppororting python3 just yet.
=> core-image-pelux: temporarily remove mopidy

conf/variant/rpi/local.conf.sample
faad2 is licensed under the GPLv2 and a commercial license for a
commercial use.
Since commercial is set in the recipe and we are not using it in the
commercial purposes, we temporarily whitelist license for faad2 package
until a better solution is found.
=> local.conf.samples: whitelist commercial for faad2

meta-intel-extras/recipes-core/base-files/base-files/intel-corei7-64/fstab, meta-intel-extras/recipes-core/base-files/base-files_%.bbappend, meta-intel-extras/recipes-support/grub/grub-efi/grubenv-copy.service, meta-intel-extras/recipes-support/grub/grub-efi/grubenv-copy.sh
A check prevented mount of EFI partition to /boot directory,
incase /boot directory already existed. This eventually result
in failing to copy the grubenv file to EFI partition. This
check is removed to fix this issue.
=> grub-efi: add fstab to meta-intel to mount EFI partition 

recipes-python/tornado/python-tornado45.bb
python-tornado 4.x is needed by Mopidy. meta-oe is currently provides
version 5 only.
=> python-tonado: add recipe

classes/core-image-pelux.bbclass
Since mopidy installation in Thud is fixed, add it back to the image.
=> core-image-pelux: add mopidy back

conf/variant/arp-qtauto/local.conf.sample, conf/variant/intel-qtauto/local.conf.sample
Auto load kernel modules necessary for proper functioning of the
Neptune 3 UI.
=> local.conf.sample: auto-load kernel modules

recipes-multimedia/mopidy/mopidy_2.2.2.bb
Make sure that python-tornado v4.5 provided by meta-pelux will be
on the image instead of newer versions provided by meta-openembedded.
=> mopidy: add dependancy on python-tornado45

recipes-multimedia/mopidy/mopidy_2.2.2.bb
Mopidy in fact rdepends on python-tornady45.
=> mopidy: fix dependancy on python-tornado45

conf/variant/arp-qtauto/local.conf.sample, conf/variant/arp/local.conf.sample, conf/variant/intel-qtauto/local.conf.sample, conf/variant/intel/local.conf.sample
A wks file used to create dual boot partitions was used to
automatically create an fstab file with mount entries for
the partitions. But since an fstab file already existed with
those entries, so it appended the new entries, resulting in
duplicate entries. Setting --no-fstab-update will ignore
generating the fstab file automatically.
=> local.conf: set WIC_CREATE_EXTRA_ARGS to --no-fstab-update

conf/variant/arp-qtauto/local.conf.sample, conf/variant/arp/local.conf.sample
faad2 is licensed under the GPLv2 and a commercial license for a
commercial use, therefore LICENSE_FLAGS is set to "commercial" in the
recipe.
The "commercial" license has been whitelisted for Intel and RPI3 in
@49178fb4c8b2fb77. Whitelist it for ARP as well.
=> local.conf.samples: whitelist commercial for faad2 on ARP

layers/b2qt/recipes-qt/automotive/neptune3-ui_git.bbappend
With neptune3, multiple applications in neptune ui
runs as separate processes. On rpi this causes some
performance issues since it doesn't have a very good
GPU. This causes a very low frame rate as well as
issues with correct rendering of the applications.
A workaround is added which runs neptune3 ui as a
single process. This fixes the performance and
rendering issues on rpi. This is a temporary fix,
until a solution is provided in neptune for this
issue.
(cherry picked from commit 1f81027db7c94c13b0cc1aeb03c86e2f4bc4db31)
=> neptune3: Force to run as single process for rpi

classes/core-image-pelux.bbclass
avs-device-sdk is needed for development of Alexa
voice service applications on PELUX.
=> core-image-pelux: add avs-device-sdk

classes/core-image-pelux.bbclass
Since swupdate package is installed on all the supported hardware
platforms, it makes no sense to separately append it to IMAGE_INSTALL
for every target.
Use IMAGE_INSTALL_append instead to install package on all the targets
by default and make code cleaner.
=> core-image-pelux: remove duplicate swupdate installs

conf/distro/pelux.conf
Changed DISTRO_VERSION to "master" to make it clear a running image
is not a stable release, but a development one.
=> pelux.conf: set DISTRO_VERSION to master

meta-rpi-extras/recipes-kernel/linux/linux-raspberrypi_%.bbappend
Qt Application Manager parses /sys/fs/cgroup/memory/memory.stat to
obtain system memory usage information, which is later reported by
the diagnostics app of Neptune 3 UI.
Enable cgroup memory by adding "cgroup_enable=memory" to the command
line, so the app functions on Raspberry Pi.
Relevant information/discussion on using cgroup memory on RPi 3:
https://www.raspberrypi.org/forums/viewtopic.php?t=203128
=> linux-raspberrypi: enable cgroup memory

recipes-support/hunspell/hunspell-dicts_%.bbappend
Added American English and German dictionaries, so they can be used by
the Qt Virtual Keyboard to perform autocomplete.
With this we cover all the Western languages supported by Neptune 3 UI.
=> huspell-dicts: add Czech, US English and German dicts

recipes-core/systemd/systemd/10-pelux-ethernet.network, recipes-core/systemd/systemd_%.bbappend
PELUX uses connman as a network manager. Having this configuration in
place was resulting in system using two network management services at
the same time and obtaining 2 IP addresses from DHCP.
=> systemd: remove network configuration

conf/variant/rpi-qtauto/local.conf.sample, conf/variant/rpi/local.conf.sample
Fixes the following warning:
NOTE: Multiple providers are available for u-boot-fw-utils...
=> local.conf: set PREFERRED_PROVIDER for u-boot-fw-utils

meta-intel-extras/recipes-kernel/linux/linux-intel_%.bbappend
Enabled Realtek PCI-Express card reader used by Intel NUC.
=> linux-intel: enable card reader for Intel NUC

classes/core-image-pelux.bbclass
The issue appears to be fixed in the mainstream.
=> core-image-pelux: remove obsolete cmake sdk fix

layers/b2qt/recipes-qt/automotive/neptune3-ui/neptune.service
Webapps such as youtube are failing on both NUC and RPI.
This environment line will be a workaround fix to both.
=> neptune.service: Workaround for webengine

classes/core-image-pelux.bbclass
We do not support swupdate for qemu, therefore the swupdate service
always fails in qemu and causes smoketests to fail.
=> core-image-pelux: remove swupdate on qemu

recipes-multimedia/mopidy/mopidy_2.2.2.bb
Mopidy is configured to look for audio files in /home/root/Music folder,
which is not present on the filesystem.
=> mopidy: deploy Music directory

classes/core-image-pelux-qtauto.bbclass, recipes-multimedia/qtivi-mopidy-plugin/qtivi-mopidy-plugin_git.bb
This recipe builds and installs Mopidy media backend plugin for Qt IVI.
=> qtivi-mopidy-plugin: add recipe

meta-intel-extras/recipes-support/grub/grub-efi_%.bbappend
All service files should have 644 permissions.
Permissions of grubenv on Ubuntu is also 644, so do the same on PELUX.
=> grub-efi: fix file permissions

recipes-core/systemd/systemd_%.bbappend
Enable kmod in systemd which makes systemd include the
systemd-load-modules.service. Without this service systemd will not
automatically load kernel modules at boot.
=> systemd: enable kmod

recipes-containers/softwarecontainer/files/io.qt.ApplicationManager.Application.json
The device node gateway was only bind mounting /dev/dri/renderD128
render node. This was sufficient for accessing non-previliged GPU
operations by neptune applications. Previously, this seemed sufficient
with the neptune calendar application running inside container. But,
recently it seems that wayland compositer require access to previliged
GPU operations. Primary node /dev/dri/card0 is required to access these
operations, so this device node is bind mounted inside the container.
=> Add device /dev/dri/card0 to device node gateway

layers/b2qt/recipes-qt/automotive/neptune3-ui/neptune.service, recipes-containers/softwarecontainer/files/softwarecontainer-agent.service
Wayland socket file name was hardcode in softwarecontainer which
resulted in failure if the wayland socket file name was changed
on the file system. Neptune provides WAYLAND_DISPLAY env variable
to define the name of the WAYLAND socket. Use this variable to
set the socket name in neptune and softwarecontainer.
=> Use WAYLAND_DISPLAY env var in neptune & softwarecontainer

scripts/Jenkinsfile
Script will abort previous running build if new build is in progress. It will be helpful especially for Pull Requests builds
=> Jenkinsfile: script for previous job interuption

scripts/Jenkinsfile
Script should be moved on top of node assignment as previous build will not be interrupted when all nodes are busy
Signed-off-by: Dmytro Iurchuk <diurchuk@luxoft.com>
=> Jenkinsfile: script for build abortion moved on top of node assignment

recipes-connectivity/connman/connman/disable_connman_dns_proxy.patch, recipes-connectivity/connman/connman_%.bbappend
DNS proxy was enabled for connman by default. This allowed
connman to route DNS traffic to itself by setting nameserver
to loopback IP in resolv.conf. Disabling the dns proxy means
that applications directly call DNS server for address
resolution instead of going through connman dns proxy.
The motivation for this is that some applications running
inside softwarecontainer requires network access and will
direct DNS traffic to the loopback IP inside the container.
However, connman is not running inside the container, hence
unable to resolve address. Disabling connman dns proxy means
that container applications will directly call DNS server
for address resolution.
This is a temporary workaround to get container applications
with network access to work. Ideally, it should be possible
to setup …
=> connman: disable dns proxy

layers/b2qt/recipes-qt/automotive/qtapplicationmanager/sc-config.yaml, recipes-containers/softwarecontainer/files/io.qt.ApplicationManager.Application.json
This runs neptune Map application in softwarecontainer.
It requires networkgateway to be configured in order to
access api.mapbox.com API which provides map information
to render. Filegateway is also configured since the
iptables used by networkgateway require to lock
/run/xtables.lock when running commands. /etc/ssl is
also mounted through filegateway. This is needed for SSL
certificates needed to access https://api.mapbox.com.
=> softwarecontainer: run neptune Map app in container

recipes-connectivity/connman/connman/disable_connman_dns_proxy.patch
Patch hunks. Refresh the patch, so it applies cleanly.
=> connman: refresh disable dns proxy patch

conf/variant/qemu-x86-64_nogfx/local.conf.sample
Currently, when one needs to run smoketests on qemu, the
local.conf file of the qemu-x86-64_nogfx variant needs to
be manually modified to enable running of the tests. The
tests and the configuration required to run these tests
are located in conf/test-scripts/local.conf.appendix file
in pelux-manifest. For running nightly smoke tests the
configuration from this file is automatically extracted
and appended to the qemu local.conf, but to run the tests
locally, one needs to copy the config to the local.conf.
This commit adds this configuration to local.conf.sample
of qemu variant, so the tests becomes part of the qemu.
With this change, the ci-scripts/yocto.groovy script in
pelux-manifest also needs to be updated to remove the
automatic copying of test config to the local.conf file. …
=> local.conf.sample: add smoketest to qemu config

classes/core-image-pelux.bbclass
We should probably not keep adding components unconditionally like this to core-image-pelux*.bbclass . Do it for connectivity-manager for now and then we need to come back and think about how we should handle "features" at some later point (soon (tm)).
Depends on https://github.com/Pelagicore/meta-bistro/pull/246 .
=> core-image-pelux: add connectivity-manager

conf/layer.conf, meta-intel-extras/conf/layer.conf, meta-rpi-extras/conf/layer.conf
Add Warrior to LAYERSERIES_COMPAT in layer.conf since the ACRN
configuration requires it.
Signed-off-by: Viktor Sjölind <vsjolind@luxoft.com>
=> layer.conf: add Warrior to LAYERSERIES_COMPAT

meta-intel-extras/recipes-core/base-files/base-files/intel-corei7-64/fstab, recipes-extended/images/pelux-image-update/arp/emmcsetup1.lua, recipes-extended/images/pelux-image-update/arp/emmcsetup2.lua, recipes-extended/images/pelux-image-update/arp/sw-description, recipes-extended/images/pelux-image-update/intel-corei7-64/emmcsetup1.lua, recipes-extended/images/pelux-image-update/intel-corei7-64/emmcsetup2.lua, recipes-extended/images/pelux-image-update/intel-corei7-64/sw-description, scripts/lib/wic/canned-wks/cfg, scripts/lib/wic/canned-wks/mkefidisk-multiboot.wks
NUC and ARP were assumed to boot from /dev/sda.
However, the boot device could be other than the
usb. In that case hardcoded device /dev/sda would
fail to boot. The solution is to use manually
generated PARTUUIDs hardcoded in wks file instead
of hardcoded device names, which could change. The
PARTUUIDs will remain the same even if the boot
device is changed. This also affected the swupdate
which also assumed the device to be /dev/sda.
Software update is modifed to use PARTLABEL to
detect the boot device. Since PARTUUID and
PARTLABEL have one to one mapping, PARTUUID
can be used in software update scripts. However,
for better readability reasons PARTLABEL are used.
=> Use PARTUUID to boot intel and ARP targets

layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune-dev.bb, layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune.bb, recipes-core/images/core-image-pelux-minimal-dev.bb, recipes-core/images/core-image-pelux-minimal.bb
Added openssh-server to non-dev images.
Also removed coreutils from dev image since it is already part of the
core-image-pelux-minimal which is inherited by dev image.
=> core-image-pelux-minimal: add ssh server to non-dev images

scripts/Jenkinsfile
In matter of meta layers replaceLayer mechanism was changed. Now meta repository dir
will be mounted within container, and all other action will take place inside. Everything
else was inerhited from pelux-manifest
Signed-off-by: Dmytro Iurchuk <diurchuk@luxoft.com>
=> Jenkinsfile: Vagrant to docker migration

conf/distro/git_describe_version.inc, conf/distro/pelux.conf, recipes-core/os-release/os-release.bbappend
In the manifests repository. Will make it so it is possible to know what revision of pelux-manfiests was used when building an image.
Assign DISTRO_VERSION with := to avoid running git describe every time DISTRO_VERSION is evaluated.
COREBASE points to the sources/poky directory of a PELUX checkout. Using "../../.repo/manifests" means that we rely on the current folder structure of a PELUX checkout to find the repository to run git describe in. Should be OK. If it ever changes we probably need to modify other paths, this will just be one more. A warning is printed by BitBake if the repository is not found and a default string is used instead.
Since the Yocto version is used in the names of tags in pelux-manifests, remove it from VERSION in os-release.bbappend by removing DISTRO_CODENAME. …
=> pelux.conf: set DISTRO_VERSION by running git describe

recipes-temporary-patches/persistence-administrator/persistence-administrator/0001-Make-snprintf-comply-with-Werror-format-security.patch, recipes-temporary-patches/persistence-administrator/persistence-administrator_%.bbappend
Fixes compilation with GCC 8 used by Thud.
Pull request: https://github.com/GENIVI/persistence-administrator/pull/5
=> persistence-administrator: add GCC 8 fix

classes/core-image-pelux.bbclass
Needed to build template-dbus-service and components based on it.
=> core-image-pelux: add gdbus-codegen-glibmm to SDK

conf/variant/arp-qtauto/local.conf.sample, conf/variant/arp/local.conf.sample, conf/variant/intel-qtauto/local.conf.sample, conf/variant/intel/local.conf.sample
Since our images have grown in size, dd-ing takes a long time. Bmap
tools allow us to take advantage of sparse files and reduce time needed
for flashing of an image.
=> local.conf:create a bmap file

layers/b2qt/recipes-qt/automotive/neptune3-ui/neptune.service
According to the Qt docs[1], if libudev support is not present, the
mouse cursor always show up unless explicitly disabled via the
environment variable.
udev packageconfig is enabled by default in qtbase, but for some
reason only works on Raspberry Pi, and not on Intel.
[1] https://doc.qt.io/Qt-5/embedded-linux.html#mouse
=> neptune3-ui: hide mouse cursor

classes/core-image-pelux.bbclass, recipes-core/udev-extraconf/udev-extraconf/0001-udev-extraconf-allow-labels-and-UUID-s-in-mount-blac.patch, recipes-core/udev-extraconf/udev-extraconf/pelux-roots.blacklist, recipes-core/udev-extraconf/udev-extraconf_%.bbappend
Will make it so pluggable mass storage devices are automatically mounted under /run/media/ when inserted.
Since PELUX has two root partitions for swupdate, one that is actually mounted at / and one that is not mounted at all, they need to be blacklisted from the script that is run when a mass storage device is
detected. If it is not, the rootfs that is not / will be mounted under /run/media/. mount.sh in udev-extraconf is extended with the functionality to use UUID:s or labels to blacklist devices so that this can be reliable done in PELUX (using the platform1 and platform2 labels).
Still some verification left to do. (E.g. not exactly sure why secondary / did not show up before the udev-extraconf patch was added on RPI.)
=> Include mount parts of udev-extraconf in Poky

classes/core-image-pelux.bbclass
Unnecessary to have one for each component. Also, most comments added on the line above do not provide any extra information, so remove many of them.
Create one "basic" group at top and one group for components that should probably be included through e.g. dependencies or a feature. Not sure. Perhaps udev-extraconf and swupdate should be in the last group as well? Punt that for now and focus on limiting number of IMAGE_INSTALL_append.
From #327 .
=> core-image-pelux: reduce number of IMAGE_INSTALL_append

layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune-dev.bb, recipes-core/images/core-image-pelux-minimal-dev.bb
tools-testapps packagegroup is comprised of tools we are not using.
LPT package alone takes about 20 minutes to build on a good machine
and occupies 250 MB of space on the filesystem.
=> core-image-pelux-minimal-dev: remove tools-testapps

classes/core-image-pelux.bbclass
We are not using sdcard anywhere and ext3 is already set in BSP layers,
e.g. meta-intel and meta-rapsberrypi.
=> core-image-pelux: remove unnecessary IMAGE_FSTYPES

layers/b2qt/recipes-multimedia/qtivi-mopidy-plugin/qtivi-mopidy-plugin_git.bb
Changelog:
- Adapt to Qt IVI 5.13
- Use Q_UNUSED for unused variables
- Avoid using sudo in Jenkins job
- Pass local user UID and GID to Docker
=> qtivi-mopidy-plugin: bump revision

classes/core-image-pelux.bbclass
Add it to the "to be restructured later" IMAGE_INSTALL_append section since currently nothing uses it. There is a command line tool (uimcli) and a test source (MSD) that can be used to verify that the basic functionality of the daemon works. See https://github.com/Pelagicore/user-identification-manager/README.md for more information.
Depends on https://github.com/Pelagicore/meta-bistro/pull/253 .
=> core-image-pelux: add user-identification-manager

layers/b2qt/recipes-qt/qt5/qtbase_%.bbappend
This packageconfig is set by bbpappend in meta-raspberrypi. We do not
need this package in PELUX.
=> qtbase: remove examples for Raspberry Pi

recipes-core/udev-extraconf/udev-extraconf_%.bbappend
lsblk is needed to extract labels and UUID:s from partitions/filesystems when checking if they are blacklisted. See 0001-udev-extraconf-allow-labels-and-UUID-s-in-mount-blac.patch .
lsblk was included before c2ca4d55701096b8710727655e23a7185cf438f2 indirectly through some dependency in tools-testapps .
=> udev-extraconf: add lsblk dependency

conf/variant/rpi-qtauto/local.conf.sample, conf/variant/rpi/local.conf.sample, meta-arp-extras/recipes-core/base-files/base-files/fstab, meta-intel-extras/recipes-core/base-files/base-files/intel-corei7-64/fstab, meta-rpi-extras/recipes-core/base-files/base-files/raspberrypi3/fstab, scripts/lib/wic/canned-wks/mkefidisk-multiboot.wks, scripts/lib/wic/canned-wks/raspberrypi.wks
A wic image will simplify adding partitions to the image and adding
labels for them.
Since root partitions now have labels, the blacklisting added in
4d4ffbaf125badc31be1af34b70f471c820ad034 will work for RPI as well.
A new partition, /media, was also added for RPI images.
=> wic image for RPI and adding media partition

layers/b2qt/recipes-qt/qt5/qtwayland/add-wayland-scanner-client-wayland-protocol-include.patch, layers/b2qt/recipes-qt/qt5/qtwayland_%.bbappend
We use eglfs as a platform plugin to run Neptune 3 UI. Moreover, it
breaks build of QtWayland 5.13 for a reason that is currently not
understood.
=> qtwayland: fix config for Raspberry Pi

layers/b2qt/recipes-multimedia/qtivi-mopidy-plugin/qtivi-mopidy-plugin_git.bb
Renamed plugin library file to libzzmedia_mopidy_experimental.so, so
it is the last one to be picked by the Qt IVI and to indicate that it
is not production ready.
=> qtivi-mopidy-plugin: rename plugin library

recipes-multimedia/pulseaudio/pulseaudio/system.pa
PELUX does not use the user level account and uses pulse level system
level. However, when using system level, a client can not access it
due to the permission problem for unix socket.
Allow anonymous access for local clients.
=> pulseaudio: allow anonymous access for UNIX clients

recipes-temporary-patches/persistence-common-object/persistence-common-object/0001-Partial-revert-of-3b28999fa9a1f7f8cd9b55ba6f8165e244.patch, recipes-temporary-patches/persistence-common-object/persistence-common-object_%.bbappend
In applications that link against persistence-common-object. See commit message in patch for details.
Upstream pr: https://github.com/GENIVI/persistence-common-object/pull/7
=> persistence-common-object: add patch for making DLT work

recipes-core/udev-extraconf/udev-extraconf/0001-udev-extraconf-allow-labels-and-UUID-s-in-mount-blac.patch, recipes-core/udev-extraconf/udev-extraconf/0002-udev-extraconf-do-not-try-to-mount-swap-partitions.patch, recipes-core/udev-extraconf/udev-extraconf_%.bbappend
Skip mounting swap partitions as they have special filesystem that
cannot and should not be mounted.
=> udev-extraconf: do not mount swap partitions

recipes-core/udev-extraconf/udev-extraconf/0002-udev-extraconf-do-not-try-to-mount-swap-partitions.patch
Patch that makes udev-extraconf skip mounting swap partitions is
missing return statement in case (mistake made in @06970f65bdd084).
=> udev-extraconf: add missing return in mount patch

meta-arp-extras/recipes-core/base-files/base-files/fstab
Wrong UUID:s added in b5219d7b55ac355474713df5ceb513d63a1ed031.
Will fix this more properly after 4.0 (do not want to break something this close to release). See #348 .
=> meta-arp-extras: fix wrong UUID:s in /etc/fstab

recipes-connectivity/connman/connman_%.bbappend
We need connman-client to work with connman. Add it to its runtime
dependencies, so it is always deployed to images together with connman.
=> connman: add connman-client to rdepends

recipes-temporary-patches/persistence-administrator/persistence-administrator/0002-Replace-unknown-oip-cpi-mandatory.target-in-systemd-.patch, recipes-temporary-patches/persistence-administrator/persistence-administrator_%.bbappend, recipes-temporary-patches/persistence-client-library/persistence-client-library/0001-Remove-D-Bus-policy-configuration-for-org.genivi.per.patch, recipes-temporary-patches/persistence-client-library/persistence-client-library_%.bbappend, recipes-temporary-patches/persistence-common-object/persistence-common-object/0002-Revert-dbus_config-Remove-dbus-configuration-file.patch, recipes-temporary-patches/persistence-common-object/persistence-common-object/0003-Install-D-Bus-policy-file-in-usr-share-dbus-1-system.patch, recipes-temporary-patches/persistence-common-object/persistence-common-object_%.bbappend
This commit only makes it so it runs without immediately exiting when trying to start the pas-daemon service. See commit messages in patch files and upstream pull requests for details.
Note: I think we should wait with pulling this into master before we have verified the full pcl vertical. Having this PR makes it easier for others to pick up the persistance-administrator fixes at least.
=> Patches to make persistance-administrator daemon run

meta-rpi-extras/recipes-bsp/boot-files/rpi-config_%.bbappend
GPU_MEM is set to 256 Mb in meta-boot2qt now and is sufficient to run
Neptune 3 UI, threfore it makes sence to save precious RAM.
=> rpi-config: do not set GPU_MEM

conf/variant/arp-qtauto/bblayers.conf.sample, conf/variant/arp-qtauto/local.conf.sample, conf/variant/arp/bblayers.conf.sample, conf/variant/arp/local.conf.sample, conf/variant/intel-qtauto/local.conf.sample, conf/variant/intel/local.conf.sample, meta-arp-extras/conf/layer.conf, meta-arp-extras/recipes-core/base-files/base-files/fstab, meta-arp-extras/recipes-core/base-files/base-files_%.bbappend, meta-intel-extras/recipes-core/base-files/base-files/intel-corei7-64/fstab, meta-intel-extras/recipes-core/base-files/base-files_%.bbappend, scripts/lib/wic/canned-wks/mkefidisk-multiboot.wks
This reverts commit 1acf4025a35a630a572d31938ada529951d6c153.
Even though automatically generating fstab from the wks file
is a nice solution, but it does not work well with the swupdate
feature. The reason being that the swupdate swu file does not
contain the fstab file that is generated for wic image. And there
seems to be no way of updating the swu file to contain the fstab
generated by wic script. So the swu file uses the base fstab from
the rpi layer. This results in the partitions mounted incorrectly
when the partition is updated using swupdate. So here we revert
to the solution that uses hard coded fstab files instead.
=> Revert "Cleanup /etc/fstab handling for Intel and ARP"

recipes-core/systemd/systemd_%.bbappend
Use 'PACKAGECONFIG +=' to add kmod, will cause systemd package
whole configuration cleared, will remove almost systemd module.
So change to use 'PACKAGECONFIG_append' to add kmod.
=> systemd: change to use 'PACKAGECONFIG_append' to add kmod

recipes-core/systemd/systemd/99-printk.conf, recipes-core/systemd/systemd_%.bbappend
Lower kernel.printk values to the ones Ubuntu has to get rid of
unnecessary low-level messages.
=> systemd: stop low-level messages on console

classes/core-image-pelux.bbclass
iproute2 is required to setup CAN devices on Linux.
=> core-image-pelux: add iproute2

conf/distro/pelux.conf
Removed DISTRO_FEATURES that are already part of DISTRO_FEATURES_DEFAULT
variable in oe-core and cleanedup syntax.
=> pelux.conf: cleanup

scripts/lib/wic/canned-wks/cfg
This has been added in @e5428651123e47d3c, since the Linux kernel
driver supplied wth Yocto "sumo" 2.5 had an issue that caused it to
crash.
The issue has resolved fixed in newer versions of the driver, so get
rid of this workaround.
=> grub: remove disabling execlist support for i915

meta-rpi-extras/recipes-bsp/boot-files/rpi-config_%.bbappend
This has unfortunately led to unstbilities in the Neptune 3 UI work.
This reverts commit c5d9825bd63bca344412bb5aa60f80223897d571.
=> Revert "rpi-config: do not set GPU_MEM"

conf/distro/pelux.conf
systemd needs PAM support for user sessions to work correctly,
otherwise XDG_RUNTIME_DIR won't be created on boot and Wayland
will complain[1]:
[FAILED] Failed to start User Manager for UID 0.
pam packageconfig has been enabled in meta-boot2qt (@ded06350f2dd23b),
and will later be merged to thud and/or warrior branche, but
prerequisite for it is pam DISTRO_FEATURE in Yocto.
[1] https://bugreports.qt.io/browse/QTBUG-75543
=> pelux.conf: add pam to DISTRO_FEATURES

meta-intel-extras/recipes-bsp/thermald/thermald_%.bbappend
thermald comes with BSP package in meta-intel and although its zero
configuration mode is normally sufficient for most systems, there is
currently no need in any thermal control.
Also, due to the lack of configuration supplied, it produces a bunch
of errors, flooding the systemd log:
sensor id 6 : No temp sysfs for reading raw temp
sensor id 6 : No temp sysfs for reading raw temp
sensor id 6 : No temp sysfs for reading raw temp
I/O warning :
failed to load external entity "/etc/thermald/thermal-conf.xml"
error: could not parse file /etc/thermald/thermal-conf.xml
sysfs open failed
I/O warning :
failed to load external entity "/etc/thermald/thermal-conf.xml"
error: could not parse file /etc/thermald/thermal-conf.xml
I/O warning :
failed to load external entity …
=> thermald: disable systemd service

conf/layer.conf
bc is required to build kernel and kernel modules with the SDK,
otherwise the following error will occur:
/bin/sh: 1: bc: not found
=> layer.conf: add bc to HOSTTOOLS

meta-intel-extras/recipes-kernel/linux/files/disable-brtfs.cfg, meta-intel-extras/recipes-kernel/linux/linux-intel_%.bbappend
During boot, kernel spends around 200ms executing raid6_select_algo()
function.
RAID6 is selected by CONFIG_BTRFS_FS, neither of which we do not need.
=> linux-intel: disable CONFIG_BTRFS_FS

layers/b2qt/recipes-qt/boot2qt-addons/qdb_%.bbappend
Qt Debug Bridge (qdb) is part of the following package groups defined
in meta-boot2qt:
- packagegroup-b2qt-automotive-addons
- packagegroup-b2qt-embedded-addons
There is no need in having this service running on PELUX images by
default. According to `systemd-analyze blame`, it takes ~3.5 seconds to
initialize it on Intel NUC:
3.491s qdbd.service
=> qdb: disable systemd service

meta-intel-extras/recipes-support/grub/grub-efi_%.bbappend
grub is by default built with the following modules: boot, linux, ext2,
fat, serial, part_msdos, part_gpt, normal, efi_gop, iso9660, configfile,
search, loadenv, test.
Many of those modules are not needed neither for PELUX, neither for a
typical embedded Linux/IVI system.
Build grub-efi with necessary modules only to reduce binary size and
threfore boot time.
=> grub-efi: strip unnecessary modules

conf/variant/smarcimx8m/local.conf.sample
meta-fsl-bsp-release has bbappend for connman that supplies some
enhanced verison of connman script with an aim to fix few issues, e.g.
"issue that 2 Ethernet port board failed to mount nfs rootfs" that
are of no concern for us.
Mask this bbappend, so it doesn't conflict with bbappend in meta-pelux.
=> variant/smarcimx8m: bbmask connman append from meta-fsl-bsp-release

conf/variant/jetson-tx2/README, conf/variant/jetson-tx2/bblayers.conf.sample, conf/variant/jetson-tx2/conf-notes.txt, conf/variant/jetson-tx2/local.conf.sample
Added cofiguration for minimal image for NVIDIA Jetson TX2.
=> variant/jetson-tx2: add configuration

meta-smarcimx8m-extras/recipes-qt/qt5/qtbase_git.bbappend
eglfs packageconfig is not enabled when Freescale SDK is used.
=> qtbase: add eglfs packageconfig for smarcimx8m

meta-tegra-extras/recipes-alexa/avs-device-sdk/avs-device-sdk_%.bbappend
Snowboy provides aarch64 binary of its library for two variants:
- aarch64-ubuntu1604
- android/armv8-aarch64
Unfortunately, linker fails to recognize their format and therefore
package build fails on Yocto/PELUX for aarch64.
Build avs-device-sdk without snowboy support for now.
A similar fix was implemented for smarcimx8m (see @8f1634dbfd167d99e).
=> avs-device-sdk: build without snowboy for jetson-tx2

conf/variant/jetson-tx2-qtauto/README, conf/variant/jetson-tx2-qtauto/bblayers.conf.sample, conf/variant/jetson-tx2-qtauto/conf-notes.txt, conf/variant/jetson-tx2-qtauto/local.conf.sample
Added cofiguration for Qt Auto + Neptune 3 UI variant for NVIDIA
Jetson TX2.
=> jetson-tx2-qtauto: add configuration

conf/variant/jetson-tx2-qtauto/local.conf.sample, conf/variant/jetson-tx2/local.conf.sample
Nothing currently gets use out of Vulkan in PELUX, but the bbappend in
meta-tegra pulls x11 DISTRO_FEATURE dependency through setting runtime
dependency on libxcb and libxcb-glx0.
=> variant/jetson-tx: mask vulkan append from meta-tegra

recipes-temporary-patches/meson/meson/0001-dependencies-dev-use-sys.prefix-to-find-googletest-a.patch, recipes-temporary-patches/meson/meson_%.bbappend, recipes-temporary-patches/meson/nativesdk-meson_%.bbappend
Should not look in /usr when bitbake:ing or building with a Yocto generated SDK. We want this fixed in Meson or in Yocto, so put it in recipes-temporary-patches. See Yocto bug report and Meson pr links in bbappend:s for more information.
=> meson: add temporary patch for not detecting gtest in /usr/src

recipes-temporary-patches/meson/meson/0001-dependencies-dev-use-sys.prefix-to-find-googletest-a.patch
Refreshed the patch added in @e391455d55ad2514fda, so it does not hunk.
=> meson: refresh gtest patch

conf/variant/jetson-tx2-qtauto/local.conf.sample, conf/variant/jetson-tx2/local.conf.sample
tegraflash is an IMAGE_TYPES defined in meta-tegra that produces set of
artifacts together with dotflash.sh scripts that can be used to flash
a system on Jetson TX boards.
=> variant/jetson-tx2: generate tegraflash images

conf/variant/common/local.conf, recipes-core/systemd/systemd_%.bbappend
systemd has a native feature that allows generation and instantiatiation
of serial-getty@.service instances for virtualizer consoles.
=> systemd: use getty-generator for vconsole instantiatiation

recipes-core/psplash/psplash/psplash-start.service, recipes-core/psplash/psplash/psplash-stop.service, recipes-core/psplash/psplash_%.bbappend
Added unit files for two services:
- psplash-start that will start psplash on system boot
- psplash-stop that will stop it right after Neptune 3 UI is started,
when user switches virtual consoles, user prompt is shown instead of
the splash screen.
At the moment, default OpenEmbedded screen is shown.
=> psplash: add systemd unit files

classes/core-image-pelux-qtauto.bbclass
Added egl-wayland wayland package for Jetson TX2 that contains the
Wayland EGL External Platform library which implements hardware
specific EGL External Platform Interface for the NVIDIA Jetson boards.
Additional info:
https://github.com/NVIDIA/egl-wayland
https://github.com/NVIDIA/eglexternalplatform
=> core-image-pelux-qtauto add egl-wayland for jetson-tx2

conf/variant/smarcimx8m-qtauto/local.conf.sample
meta-fsl-bsp-release contains psplash patches that conflict with the
ones in meta-pelux layer.
PELUX ships with its own bootsplash for psplash.
=> variant/smarcimx8m-qtauto: mask psplash append

recipes-support/dnsmasq/dnsmasq_%.bbappend
This bbappend has been moved here from meta-bistro (19124921a6).
dnsmasq is a runtime dependency of lxc, but is not needed for PELUX.
=> dnsmasq: disable systemd service

conf/variant/arp-intel-qtauto/bblayers.conf.sample, conf/variant/arp-intel/bblayers.conf.sample
Since meta-intel-extras has been removed and its bbappends were moved
to dynamic-layers/intel, remove the meta-layer from bblayers.conf for
the ARP Intel variants.
=> variant/arp-intel: remove meta-intel-extras from bblayers

conf/variant/arp-intel-qtauto/local.conf.sample, conf/variant/arp-intel/local.conf.sample
=> variant/arp-intel: remove unnecessary machine conf inclusion

conf/variant/jetson-tx2-qtauto/local.conf.sample, conf/variant/jetson-tx2/local.conf.sample
Kernel modules are not shipped for some reason, but do contain a lot of
the essential drivers, e.g. PCI-Express.
=> variant/jetson-tx2: install kernel-modules

dynamic-layers/b2qt/recipes-qt/automotive/qtapplicationmanager-sc.inc
Currently shipped configuration file for the softwarecontainer is
platform specific and does not work on Jetson TX2, so do not run
Neptune apps inside softwarecontainer for now, until a separate
config is provided.
=> qtapplicationmanager: do not run apps in container on Jetson TX2

conf/layer.conf
In dedea8cf05 the only bbappend for the meta-smarcimx8m was moved to
dynamics-layers folder, but path to it was not added to layer.conf.
=> layer.conf: add smarcimx8m dynamic layer

dynamic-layers/smarcimx8m/recipes-qt/qt5/packagegroup-qt5-toolchain-target.bbappend
For whatever reason, qtwebkit-dev is pulled in through this runtime
dependency. Unfortunately, package does not build due to not being able
to find X11/Xlib.h header, even though it is built without x11 support.
qtwebkit is anyway deprecated and Neptune 3 UI uses QtWebEngine instead
for a web-browser.
=> packagegroup-qt5-toolchain-target: remove qtwebkit-dev from rdepends

dynamic-layers/smarcimx8m/recipes-qt/qt5/qtbase_git.bbappend
Fixed a typo in the qtbase recipe for the smarcimx8m.
```dynamic-layers/smarcimx8m/recipes-qt/qt5/qtbase_git.bbappend```
Signed-off-by: Dimitris Tassopoulos <dimtass@gmail.com>
=> Fixed typo in qtbase for the smarcimx8m

dynamic-layers/b2qt/recipes-qt/automotive/qtapplicationmanager-sc.inc
If using += the behaviour is not defined in case the variable
hasn't been set before bitbake parses this line. There is a risk
that the variable is (re)set in the main recipe if _append is
not used.
Signed-off-by: Johan Ederonn <jederonn@luxoft.com>
=> qtapplicationmanager-sc.inc: Replace += with _append

recipes-multimedia/mopidy/mopidy_2.3.1.bb
Changed dependency from python-tornado45 to python-tornado from
meta-openembedded as this version supports python-tornado 5 and 6.
=> mopidy: bump to 2.3.1

conf/layer.conf
LAYERSERIES_COMPAT in meta-smarcimx8m is set to 'sumo', but the layer
itself builds with thud perfectly fine.
Append layer's compatibility until it is upgraded in the upstream layer.
=> layer.conf: add thud to LAYERSERIES_COMPAT for smarcimx8m

dynamic-layers/b2qt/recipes-qt/automotive/neptune3-ui/neptune
There is a change in Qt 5.14, where the XDG_RUNTIME_DIR cannot be
/tmp since the permission for that dir is not read-only for the
current user (i.e. root). The default value of XDG_RUNTIME_DIR as
defined in meta-boot2qt is /run/user/0 so let's use this also.
TODO: Consider to reuse the default Qt config as defined in the
boot2qt addons and only apply modifications applicable for PELUX.
Signed-off-by: Johan Ederonn <jederonn@luxoft.com>
=> /etc/defaults/neptune: Change XDG_RUNTIME_DIR

conf/distro/pelux.conf
Due to some issues which cannot be fixed right now:
- (BLOCKER) Qt 5.14 AS candidate results in build error
ERROR: Required build target 'neptune3-ui' has no buildable providers.
Missing or unbuildable dependency chain was: [
'neptune3-ui',
'qtapplicationmanager-native',
'qtapplicationmanager-native-softwarecontainer-native']
- With Qt 5.13, Neptune3-UI cannot run applications in container
(workaround is to not provide sc-config.yaml to neptune3-ui)
- Sometimes at system shutdown, the softwarecontainer-agent does
not stop within maximum timeout
=> pelux.conf: Temporarily disable DISTRO_FEATURE process-containment

classes/core-image-pelux-qtauto.bbclass, dynamic-layers/b2qt/recipes-multimedia/qtivi-mopidy-plugin/qtivi-mopidy-plugin_git.bb
The intention has been that the QtIvi Media mopidy plugin shall
not be selected since it's still experimental and not complete.
The problem is that it is still selected due to incorrect naming.
The method QIviServiceManagerPrivate::isSimulation returns TRUE
if the QtIvi plugin library name contains _simulation.
=> qtivi-mopidy-plugin_git.bb: Add suffix _simulation to lib

recipes-multimedia/mopidy/mopidy_2.3.1.bb
python-tornado that is a dependancy of mopidy requires python-futures package.
=> mopidy: add python-futures to rdepends

recipes-multimedia/mopidy/mopidy_2.3.1.bb
python-tornado depends on ntpath module which was moved to python-misc
package on Yocto "Warrior".
=> mopidy: add python-misc to rdepends

dynamic-layers/b2qt/recipes-qt/automotive/neptune3-ui/neptune, dynamic-layers/b2qt/recipes-qt/automotive/neptune3-ui/pelux.conf
Can not use %u in EnvironmentFile since it will not be converted
to current user.
Problem to fix: If you download apps in Neptune, these will be installed in /home/%u/.local/share and not in /home/root.
=> neptune3-ui: Move Environment setting for HOME

conf/variant/arp-intel/multiconfig/sos.conf, conf/variant/arp-intel/multiconfig/uos.conf, dynamic-layers/acrn-layer/recipes-core/images/core-image-pelux-sos.bb, dynamic-layers/acrn-layer/recipes-vms/acrn-vm-init/acrn-vm-init/acrn-vm-init.service, dynamic-layers/acrn-layer/recipes-vms/acrn-vm-init/acrn-vm-init/acrn-vm-init.sh, dynamic-layers/acrn-layer/recipes-vms/acrn-vm-init/acrn-vm-init_1.0.0.bb, dynamic-layers/acrn-layer/recipes-vms/android-x86/android-x86-vm/.gitignore, dynamic-layers/acrn-layer/recipes-vms/android-x86/android-x86-vm/LICENSE, dynamic-layers/acrn-layer/recipes-vms/android-x86/android-x86-vm/android-x86-vm.service, dynamic-layers/acrn-layer/recipes-vms/android-x86/android-x86-vm/launch_android_x86.sh, dynamic-layers/acrn-layer/recipes-vms/android-x86/android-x86-vm_1.0.0.bb, dynamic-layers/acrn-layer/recipes-vms/pelux/pelux-vm/LICENSE, dynamic-layers/acrn-layer/recipes-vms/pelux/pelux-vm/launch_pelux.sh, dynamic-layers/acrn-layer/recipes-vms/pelux/pelux-vm/pelux-vm.service, dynamic-layers/acrn-layer/recipes-vms/pelux/pelux-vm_1.0.0.bb, dynamic-layers/acrn-layer/recipes-vms/targets/acrn-vm-targets/acrn-vm1.target, dynamic-layers/acrn-layer/recipes-vms/targets/acrn-vm-targets/acrn-vm2.target, dynamic-layers/acrn-layer/recipes-vms/targets/acrn-vm-targets/acrn-vm3.target, dynamic-layers/acrn-layer/recipes-vms/targets/acrn-vm-targets_1.0.0.bb
This PR adds config and recipes used to create Service-OS and User-OS images using PELUX.
It should be fairly non-intrusive and is tested and verified to work with ARP/Intel. However, there are some things to consider:
It is based on poky warrior since some things in the setup is broken in thud
This PR is a rebase of #296 on latest master as of 2020-01-14
Workarounds used in that PR are now obsolete so should be fine to merge
=> Add build configuration Acrn

recipes-temporary-patches/gstreamer/gstreamer1.0-plugins-bad_%.bbappend
Wayland was temporarily removed a few years! ago due to a
compilation error for 64-bit arch. Should have been fixed now.
Signed-off-by: Johan Ederonn <jederonn@luxoft.com>
=> gstreamer1.0: Re-enable wayland support
