recipes-core/images/core-image-pelux-qt.bb
recipes-core/softwarecontainer/files/io.qt.ApplicationManager.Application.json
recipes-core/softwarecontainer/files/softwarecontainer-agent.service
recipes-core/softwarecontainer/softwarecontainer.bbappend
recipes-qt/automotive/neptune-ui/neptune.service
recipes-qt/automotive/neptune-ui_git.bbappend
recipes-qt/automotive/qtapplicationmanager/sc-config.yaml
recipes-qt/automotive/qtapplicationmanager_git.bbappend

Configure appman to produce softwarecontainer-plugin
Configure neptune to use software container for com.pelagicore.radio app
Add qtapplicationmanager_git.bbappend file to provide necessary capabilities
Signed-off-by: kursat <kursat.kobya@pelagicore.com>

Configure meta-pelux to integrate SC and Appman

---

scripts/mkefi_wrap

Add script for speeding up the process of putting images on SD-cards and
USB-sticks.
Signed-off-by: Viktor Sjölind <viktor.sjolind@pelagicore.com>

scripts: add mkefiWrap script

---

README.md

Who else is reading this in 2017?

README.md: update copyright

---

layers/poky/patch/0001-Fix-automated-runtime-testing-using-SystemdbootTarge.patch

This patch should be removed once it is mainlined.

poky: Patch automated testing script and bbclasses

---

recipes-example/template-service/template-service.bb

template-service: Fix github mirror

---

LICENSE
conf/distro/pelux.conf
conf/layer.conf
recipes-containers/softwarecontainer/softwarecontainer.bbappend
recipes-core/base-files/base-files_%.bbappend
recipes-core/images/core-image-pelux-qtauto.bb
recipes-core/images/core-image-pelux.bb
recipes-example/template-library/template-library.bb
recipes-example/template-service/template-service.bb
recipes-qt/automotive/neptune-ui_git.bbappend
recipes-qt/automotive/qtapplicationmanager_git.bbappend
scripts/mkefi_wrap

Add SPDX-License-Identifier to recipes

---

README.md

README.md: Add layer rationale and content explanation

---

README.md

README.md: describe relation with meta-bistro

---

meta-intel-extras/README.md
meta-rpi-extras/README.md

BSP layers: update README with correct names

---

recipes-temporary-patches/gstreamer/gstreamer1.0-plugins-bad_%.bbappend
recipes-temporary-patches/gstreamer/gstreamer1.0-plugins-base_%.bbappend
recipes-temporary-patches/gstreamer/gstreamer1.0_%.bbappend

Remove gstreamer patches, are now in meta-ivi

---

conf/variant/intel-qtauto/README
conf/variant/intel/README
conf/variant/rpi-qtauto/README
conf/variant/rpi/README

add short README for each variant

---

conf/variant/intel-qtauto/conf-notes.txt
conf/variant/intel/conf-notes.txt
conf/variant/rpi-qtauto/conf-notes.txt
conf/variant/rpi/conf-notes.txt

conf-notes: add -dev images to listing

---

conf/variant/qemu-x86-64_nogfx/README
conf/variant/qemu-x86-64_nogfx/bblayers.conf.sample
conf/variant/qemu-x86-64_nogfx/conf-notes.txt
conf/variant/qemu-x86-64_nogfx/local.conf.sample

Signed-off-by: Alberto Mardegan <amardegan@luxoft.com>

conf/variant: Add non graphical qemu variant

---

layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune-dev.bb
recipes-core/images/core-image-pelux-minimal-dev.bb
recipes-core/systemd/systemd/10-pelux-ethernet.network
recipes-core/systemd/systemd_%.bbappend

These two commits issues are valid for morty as well. This is part of preparation for release of PELUX.

Backporting commits from master to morty

---

layers/b2qt/recipes-qt/automotive/neptune-ui_git.bbappend

Fixes an issue where Neptune would crash immediately at startup.

Bump version of Neptune

---

conf/variant/common/local.conf
recipes-core/systemd/systemd_%.bbappend

Configuring STATIC_IP_ADDRESS fixes the issue with poky ssh tests.

Add configurable static ip address to the image

---

conf/distro/pelux.conf
conf/variant/common/bblayers.conf
layers/b2qt/recipes-qt/automotive/neptune-ui/neptune.service
layers/b2qt/recipes-temporary-patches/qt5/qtbase_%.bbappend
recipes-core/systemd/systemd_%.bbappend

This adds some changes needed to adapt to the rocko release of poky for meta-pelux.

Update meta-pelux to rocko

---

layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune-dev.bb
recipes-core/images/core-image-pelux-minimal-dev.bb

packagegroup: Change to use debug-utils for dev images

---

conf/distro/pelux.conf

pelux.conf: DISTRO_FEATURES in alphabetical order

---

scripts/qemu_launcher.sh

Signed-off-by: Chuan Jin <cjin@luxoft.com>

Add QEMU launch script

---

scripts/gdb_helper

Signed-off-by: Chuan Jin <cjin@luxoft.com>

Add gdb helper script for remote debugging

---

scripts/qemu_launcher

Signed-off-by: Chuan Jin <cjin@luxoft.com>
I feel it is better to keep the same convention with other scripts in the same folder. And this script will be shipped with SDK, it will make more sense to remove the extension

Rename script to remove extension

---

scripts/qemu_launcher

Signed-off-by: Chuan Jin <cjin@luxoft.com>

Make static IP configurable

---

scripts/Jenkinsfile

This enables easy testing of upcoming changes to meta-pelux with
pelux-manifests for a full PELUX build.

Add a Jenkinsfile to test the layer

---

README.md
conf/distro/pelux.conf
conf/variant/common/local.conf
conf/variant/qemu-x86-64_nogfx/bblayers.conf.sample
layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune-dev.bb
layers/b2qt/recipes-qt/automotive/neptune-ui_git.bbappend
meta-intel-extras/recipes-bsp/acpid/acpid_2.%.bbappend
meta-intel-extras/recipes-bsp/acpid/files/powerbtn
meta-intel-extras/recipes-bsp/acpid/files/powerbtn.sh
recipes-core/images/core-image-pelux-minimal-dev.bb
recipes-core/systemd/systemd_%.bbappend
scripts/gdb_helper
scripts/qemu_launcher

This includes all commits made on rocko since the release of PELUX 1.0 on pyro, except:
* Anything that is rocko specific (some DISTRO_FEATURES, layer names changed etc)
* Everything having to do with SWUpdate
* QtAuto packagegroups
* Including the Jenkinsfile

Bump pyro branch to include some of the rocko commits

---

classes/core-image-pelux.bbclass
conf/variant/arp-qtauto/README
conf/variant/arp-qtauto/bblayers.conf.sample
conf/variant/arp-qtauto/conf-notes.txt
conf/variant/arp-qtauto/local.conf.sample
conf/variant/arp/README
conf/variant/arp/bblayers.conf.sample
conf/variant/arp/conf-notes.txt
conf/variant/arp/local.conf.sample

Signed-off-by: tansari <tansari@luxoft.com>

Add ARP variant to PELUX

---

conf/variant/arp-qtauto/local.conf.sample
conf/variant/arp/local.conf.sample

Signed-off-by: tansari <tansari@luxoft.com>

Fix bug: set MACHINE="arp" for ARP local conf

---

README.md

README: fix dependencies headline

---

recipes-extended/images/pelux-image-update.inc

This reverts commit cefa914dc715fd4d865a14000cef7c4633550427.

Revert "pelux-image-update: fix FILESEXTRAPATHS"

---

classes/core-image-pelux.bbclass

Signed-off-by: tansari <tansari@luxoft.com>

Add arp-driver to arp pelux image

---

conf/layer.conf

layer.conf: add LAYERSERIES for sumo

---

LICENSE

Signed-off-by: Oleksandr Kravchuk <dev@sashko.rv.ua>

LICENSE: add Luxoft Sweden copyright

---

conf/distro/pelux.conf

pelux.conf: fix DISTRO_NAME

---

conf/variant/common/bblayers-qtauto.conf
conf/variant/common/bblayers.conf
conf/variant/common/local.conf
layers/b2qt/recipes-qt/automotive/neptune3-ui/neptune.service
layers/b2qt/recipes-qt/automotive/neptune3-ui_git.bbappend
layers/b2qt/recipes-qt/automotive/qtapplicationmanager_git.bbappend
layers/b2qt/recipes-qt/qt5/qttools_%.bbappend

Let me know if there is any other commit to cherrypick.

topic/qt5.11: cherrypick commits from the branch to merge them to master

---

conf/variant/intel-qtauto/local.conf.sample

swupdate: fix dual boot partitions for intel-qtauto image

---

conf/distro/pelux.conf

pelux.conf: change DISTRO_VERSION to 2.0

---

classes/core-image-pelux.bbclass
conf/variant/arp-qtauto/local.conf.sample
conf/variant/arp/local.conf.sample
recipes-extended/images/pelux-image-update.inc
recipes-extended/images/pelux-image-update/arp/emmcsetup.lua
recipes-extended/images/pelux-image-update/arp/sw-description

swupdate: Add support for arp target

---

meta-intel-extras/recipes-support/grub/grub-efi_%.bbappend

this issue appears on our CI/CD while building master now as well.

grub-efi: fix package installation

---

classes/core-image-pelux.bbclass

Add CAN utilities and Socket CAN modules

---

conf/layer.conf

layer.conf: fix LAYERSERIES_COMPAT

---

README.md

README.md: minor formatting fixes

---

recipes-temporary-patches/gammaray/gammaray_git.bbappend

gammaray: add bbappend with temp rpath fix

---

conf/variant/rpi-qtauto/local.conf.sample

local.conf.sample: remove whitespaces

---

README.md

README: fix dependancy repos URIs

---

classes/core-image-pelux.bbclass
meta-rpi-extras/recipes-bsp/boot-files/rpi-config_%.bbappend
recipes-devtools/python/python-pykka_1.2.1.bb
recipes-multimedia/mopidy/mopidy/0001-default.conf-Use-pulseaudio-as-default-output.patch
recipes-multimedia/mopidy/mopidy/0002-local-ext.conf-Replace-XDG_MUSIC_DIR-with-a-hardcode.patch
recipes-multimedia/mopidy/mopidy/mopidy.service
recipes-multimedia/mopidy/mopidy_2.1.0.bb
recipes-multimedia/pulseaudio/pulseaudio/pulseaudio.service
recipes-multimedia/pulseaudio/pulseaudio/system.pa
recipes-multimedia/pulseaudio/pulseaudio_%.bbappend

This PR integrates the Mopidy media playback service in PELUX. It also integrates PulseAudio and enables sound on the RaspberryPi.

Mopidy integration

---

classes/core-image-pelux.bbclass
meta-rpi-extras/recipes-bsp/boot-files/rpi-config_%.bbappend
recipes-devtools/python/python-pykka_1.2.1.bb
recipes-multimedia/mopidy/mopidy/0001-default.conf-Use-pulseaudio-as-default-output.patch
recipes-multimedia/mopidy/mopidy/0002-local-ext.conf-Replace-XDG_MUSIC_DIR-with-a-hardcode.patch
recipes-multimedia/mopidy/mopidy/mopidy.service
recipes-multimedia/mopidy/mopidy_2.1.0.bb
recipes-multimedia/pulseaudio/pulseaudio/pulseaudio.service
recipes-multimedia/pulseaudio/pulseaudio/system.pa
recipes-multimedia/pulseaudio/pulseaudio_%.bbappend

Those changes have already been reviewed and accepted to master, I will then merge the PR right away.

Cherry-Pick Mopidy commits from 'master' to 'sumo'

---

recipes-temporary-patches/qt5/qtbase_%.bbappend

CI/CD currently fails on rocko due to this.

Cherry pick gammaray fix from master to rocko

---

layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune-dev.bb
recipes-core/images/core-image-pelux-minimal-dev.bb

core-image-pelux: add vim to dev images

---

conf/layer.conf

layer: add thud to LAYERSERIES_COMPAT

---

meta-intel-extras/conf/layer.conf
meta-rpi-extras/conf/layer.conf

Add thud to LAYERSERIES_COMPAT for Intel and RPI BSP layers

---

conf/variant/common/bblayers.conf

Yocto "Thud" depends on this layer.

bblayers.conf: add meta-filesystems

---

recipes-core/os-release/os-release.bbappend

os-release: add recipe

---

recipes-temporary-patches/gammaray/gammaray_git.bbappend

gammaray: make bbappend version universal

---

conf/distro/pelux.conf

pelux.conf: set DISTRO_VERSION to 3.0

---

layers/b2qt/recipes-qt/automotive/qtapplicationmanager_git.bbappend

This revision will include the fix made to
Appman's software container plugin

Update Qt Application Manager revision

---

conf/variant/common/bblayers-qtauto.conf

bblayers-qtauto.conf: cleanup

---

scripts/Jenkinsfile

Jenkinsfile: Change variant list handling

---

layers/b2qt/recipes-qt/automotive/neptune3-ui/neptune.service

neptune.service: update to use correct config filename

---

recipes-multimedia/mopidy/mopidy_2.2.2.bb

mopidy: bump to 2.2.2

---

recipes-temporary-patches/qtivi/qtivi_git.bbappend

Patches were sent to meta-boot2qt:
- https://codereview.qt-project.org/#/c/252871/
- https://codereview.qt-project.org/#/c/252872/

qtivi: add temporary bbappend

---

README.md

README: update copyrights

---

recipes-extended/images/pelux-image-update.inc
recipes-extended/images/pelux-image-update/arp/emmcsetup1.lua
recipes-extended/images/pelux-image-update/arp/emmcsetup2.lua
recipes-extended/images/pelux-image-update/arp/sw-description
recipes-extended/images/pelux-image-update/intel-corei7-64/emmcsetup1.lua
recipes-extended/images/pelux-image-update/intel-corei7-64/emmcsetup2.lua
recipes-extended/images/pelux-image-update/intel-corei7-64/sw-description
recipes-extended/images/pelux-image-update/raspberrypi3/emmcsetup1.lua
recipes-extended/images/pelux-image-update/raspberrypi3/emmcsetup2.lua
recipes-extended/images/pelux-image-update/raspberrypi3/sw-description
recipes-swupdate/swupdate/swupdate/swupdate.cfg
recipes-swupdate/swupdate/swupdate/swupdate.service
recipes-swupdate/swupdate/swupdate_%.bbappend

swupdate: run as a service

---

conf/distro/pelux.conf

pelux.conf: set DISTRO_VERSION to 3.1

---

classes/core-image-pelux.bbclass

- avs-device-sdk
- aac-sdk
- portaudio-v19

core-image-pelux.bbclass: add alexa sdks

---

classes/core-image-pelux.bbclass

This PR has been merged bypassing the review process by force-pushing
to the PR branch complitely different change after the original one was
reviewed, discussed and approved.
This reverts commit 25ee208a3b08848363678f84b3542f6e8598d15d.

Revert "core-image-pelux.bbclass: add alexa avs-device-sdk"

---

layers/b2qt/recipes-core/images/core-image-pelux-qtauto-neptune-dev.bb
layers/b2qt/recipes-qt/qt5/qtwayland_%.bbappend

- Add qmlscene for qml debugging and testing.
- add wayland examples to get custom compositor

qt: add tooling for qt integration

---

recipes-swupdate/swupdate/swupdate_%.bbappend

- swupdate-progress.service
- swupdate-usb@.service

swupdate: remove non-essential swupdate services

---

recipes-multimedia/qtivi-mopidy-plugin/qtivi-mopidy-plugin_git.bb

Changelog:
- Remove unused variables
- Comment out setCurrentIndex
- Cleanup Media Indexer Backend
- Fix race condition in retrieving tracklist
- Fix path to MediaIndexer interface

qtivi-mopidy-plugin: bump revision

---

conf/variant/arp-qtauto/local.conf.sample
conf/variant/intel-qtauto/local.conf.sample

Now systemd-kmod loads kernel modules.

local.conf.sample: remove kernel modules auto-loading

---

classes/core-image-pelux.bbclass

core-image-pelux: add meson to SDK

---

conf/variant/arp-qtauto/conf-notes.txt
conf/variant/arp/conf-notes.txt
conf/variant/intel-qtauto/conf-notes.txt
conf/variant/intel/conf-notes.txt
conf/variant/rpi-qtauto/conf-notes.txt
conf/variant/rpi/conf-notes.txt

variant/conf: Specify all the buildable images

---

conf/variant/arp-qtauto/bblayers.conf.sample
conf/variant/arp/bblayers.conf.sample
meta-arp-extras/conf/layer.conf
meta-arp-extras/recipes-core/base-files/base-files/fstab
meta-arp-extras/recipes-core/base-files/base-files_%.bbappend

meta-arp-extras: new fstab for ARP 
conf/variant: include meta-arp-extras

Arp partitioning

---

recipes-multimedia/mopidy/mopidy_2.2.3.bb

Bugfix release. Changelog:
https://docs.mopidy.com/en/latest/changelog/#v2-2-3-2019-06-20

mopidy: bump to 2.2.3

---

conf/variant/arp-qtauto/local.conf.sample
conf/variant/arp/local.conf.sample
conf/variant/intel-qtauto/local.conf.sample
conf/variant/intel/local.conf.sample

variant/local.conf.sample: Include bz2 type

---

README.md

README: fix copyright display on GitHub

---

recipes-core/systemd/systemd_%.bbappend

systemd: cleanup bbappend

---

conf/distro/pelux.conf

pelux.conf: remove excess DISTRO_FEATURES

---

recipes-containers/softwarecontainer/softwarecontainer_%.bbappend

softwarecontainer: fix systemd unit file permissions

---

recipes-config/systemd-resource-control/slices/connectivity.slice
recipes-config/systemd-resource-control/slices/ui.slice
recipes-config/systemd-resource-control/systemd-resource-control.bb
recipes-config/systemd-resource-control/systemd-resource-control/LICENSE

Add a bunch of slice units for the future use.

systemd-resource-control: add recipe

---

recipes-config/systemd-resource-control/services/service.neptune.conf
recipes-config/systemd-resource-control/systemd-resource-control.bb

systemd-resource-control: add neptune3-ui to ui slice

---

classes/core-image-pelux.bbclass

core-image-pelux: add systemd-resource-control

---

conf/variant/smarcimx8m/README
conf/variant/smarcimx8m/bblayers.conf.sample
conf/variant/smarcimx8m/conf-notes.txt
conf/variant/smarcimx8m/local.conf.sample

Added local.conf and bblayers.conf for smarcimx8m (SMARC-iMX8M).

variant/smarcimx8m: add configs

---

conf/variant/smarcimx8m-qtauto/README
conf/variant/smarcimx8m-qtauto/bblayers.conf.sample
conf/variant/smarcimx8m-qtauto/conf-notes.txt
conf/variant/smarcimx8m-qtauto/local.conf.sample

variant/smarcimx8m-qtauto: add configuration

---

conf/variant/jetson-tx2/bblayers.conf.sample
meta-tegra-extras/conf/layer.conf

Added meta-layer for PELUX specific dynamic additions and modifications
to meta-tegra.

meta-tegra-extras: add meta layer

---

recipes-core/systemd/systemd_%.bbappend

systemd: merge do_install_append functions

---

recipes-temporary-patches/qtivi/qtivi_git.bbappend

https://codereview.qt-project.org/c/yocto/meta-boot2qt/+/252871

qtivi: remove append with upstreamed fixes

---

layers/b2qt/recipes-qt/automotive/neptune3-ui/neptune

neptune3-ui: fix DBUS_SESSION_BUS_ADDRESS

---

conf/variant/arp-intel-qtauto/conf-notes.txt
conf/variant/arp-intel/conf-notes.txt

variant/arp-intel fix variant name in conf-notes

---

conf/variant/arp-intel-qtauto/bblayers.conf.sample
conf/variant/arp-intel/bblayers.conf.sample

variant/arp-intel: remove meta-arp from bblayers

---

classes/core-image-pelux-qtauto.bbclass

Signed-off-by: Johan Ederonn <jederonn@luxoft.com>

core-image-pelux-qtauto.bbclass: Add qtmqtt and qtserialport
